language: dart
sudo: false
dart:
  # Do not run on Dart stable until there is a stable release >= 2.0.0.
  #- stable
  - dev
matrix:
  allow_failures:
    - dart: "dev"
cache:
  directories:
    - $HOME/.pub-cache/hosted
script:
  - RUN_CHECKER=0 TEST_EXAMPLES=0 ./scripts/presubmit.sh
before_install:
  - . scripts/install_dependencies.sh
